[package]
name        = "ohos-resource-manager-binding"
version     = "0.1.3"
edition     = "2021"
license     = "MIT OR Apache-2.0"
description = "OpenHarmony's resource manager binding for rust"

[lints]
workspace = true

[features]
default = ["napi"]

# Using napi-ohos to create a raw file manager
napi = ["dep:napi-ohos"]


api-13 = ["ohos-resource-manager-sys/api-13"]
api-14 = ["api-13", "ohos-resource-manager-sys/api-14"]
api-15 = ["api-14", "ohos-resource-manager-sys/api-15"]
api-16 = ["api-15", "ohos-resource-manager-sys/api-16"]
api-17 = ["api-16", "ohos-resource-manager-sys/api-17"]
api-18 = ["api-17", "ohos-resource-manager-sys/api-18"]
api-19 = ["api-18", "ohos-resource-manager-sys/api-19"]
api-20 = ["api-19", "ohos-resource-manager-sys/api-20"]

[dependencies]
ohos-resource-manager-sys = { workspace = true }
napi-ohos                 = { workspace = true, optional = true }
