[package]
name        = "ohos-sensor-binding"
version     = "0.1.0"
edition     = "2021"
license     = "MIT OR Apache-2.0"
description = "OpenHarmony's sensor binding for rust"

[lints]
workspace = true

[features]
api-13 = []

[dependencies]
ohos-sensor-sys = { workspace = true }
ohos_enum_macro = { workspace = true }
