[package]
name        = "ohos-native-buffer-sys"
version     = "0.0.1"
edition     = "2021"
license     = "MIT OR Apache-2.0"
description = "OpenHarmony's native buffer binding for rust"

[dependencies]

[features]
default = []
api-13  = []
api-15  = ["api-13"]
api-20  = ["api-15"]
