[package]
name        = "ohos-asset-sys"
version     = "0.0.1"
edition     = "2021"
license     = "MIT OR Apache-2.0"
description = "OpenHarmony's asset binding for rust"

[dependencies]
[features]
default = []
api-14  = []
api-18  = ["api-14"]
api-20  = ["api-18"]
