[package]
name        = "ohos-native-buffer-binding"
version     = "0.1.0"
edition     = "2021"
license     = "MIT OR Apache-2.0"
description = "OpenHarmony's native buffer binding for rust"

[lints]
workspace = true

[dependencies]
ohos-native-buffer-sys = { workspace = true }
ohos-native-window-sys = { workspace = true }
