[package]
name        = "ohos-native-window-sys"
version     = "0.0.1"
edition     = "2021"
license     = "MIT OR Apache-2.0"
description = "OpenHarmony's native window binding for rust"

[dependencies]
ohos-native-buffer-sys = { workspace = true }
[features]
default = []
api-13  = []
api-19  = ["api-13"]
