[package]
name        = "ohos-native-window-binding"
version     = "0.1.1"
edition     = "2021"
license     = "MIT OR Apache-2.0"
description = "OpenHarmony's native window binding for rust"

[lints]
workspace = true

[features]
default = []
api-13  = ["ohos-native-window-sys/api-13", "ohos-native-buffer-binding/api-13"]
api-14  = ["api-13", "ohos-native-window-sys/api-14", "ohos-native-buffer-binding/api-14"]
api-15  = ["api-14", "ohos-native-window-sys/api-15", "ohos-native-buffer-binding/api-15"]
api-18  = ["api-15", "ohos-native-window-sys/api-18", "ohos-native-buffer-binding/api-18"]
api-19  = ["api-18", "ohos-native-window-sys/api-19", "ohos-native-buffer-binding/api-19"]
api-20  = ["api-19", "ohos-native-window-sys/api-20", "ohos-native-buffer-binding/api-20"]

[dependencies]
ohos-native-window-sys     = { workspace = true }
ohos-native-buffer-sys     = { workspace = true }
ohos_enum_macro            = { workspace = true }
ohos-native-buffer-binding = { workspace = true }
libc                       = { workspace = true }
