[package]
name    = "ohos-event-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
[features]
default = []
api-14  = []
api-15  = ["api-14"]
api-17  = ["api-15"]
api-18  = ["api-17"]
api-19  = ["api-18"]
api-20  = ["api-19"]
