[package]
name        = "ohos-resource-manager-sys"
version     = "0.1.0"
edition     = "2021"
license     = "MIT OR Apache-2.0"
description = "OpenHarmony's resource_manager binding for rust"

[dependencies]
napi-sys-ohos = { workspace = true }

[features]
default = []
api-18  = []
api-20  = ["api-18"]
