[package]
name        = "ohos-image-native-sys"
version     = "0.0.1"
edition     = "2021"
license     = "MIT OR Apache-2.0"
description = "OpenHarmony's native image binding for rust"

[dependencies]
napi-sys-ohos             = { workspace = true }
ohos-native-buffer-sys    = { workspace = true }
ohos-resource-manager-sys = { workspace = true }

[features]
default = []
api-13  = []
api-15  = ["api-13"]
api-18  = ["api-15"]
api-19  = ["api-18"]
api-20  = ["api-19"]
