[package]
name        = "ohos-accessibility-sys"
version     = "0.0.1"
edition     = "2021"
license     = "MIT OR Apache-2.0"
description = "OpenHarmony's accessibility binding for rust"

[dependencies]

[features]
default = []
api-13  = []
api-15  = ["api-13"]
