[package]
name        = "ohos-hilogs-sys"
version     = "0.0.2"
edition     = "2021"
license     = "MIT OR Apache-2.0"
description = "OpenHarmony's hilog binding for rust"


[lints.rust]
improper_ctypes             = "allow"
improper_ctypes_definitions = "allow"

[dependencies]

[features]
default = []
api-13  = []
api-14  = ["api-13"]
api-15  = ["api-14"]
api-16  = ["api-15"]
api-17  = ["api-16"]
api-18  = ["api-17"]
api-19  = ["api-18"]
api-20  = ["api-19"]
api-21  = ["api-20"]
api-22  = ["api-21"]
