[package]
name        = "ohos-web-binding"
version     = "0.1.0"
edition     = "2021"
license     = "MIT OR Apache-2.0"
description = "OpenHarmony's web binding for rust"

[lints]
workspace = true

[dependencies]
ohos-web-sys    = { workspace = true }
bitflags        = { workspace = true }
ohos_enum_macro = { workspace = true }

[features]
default = []
api-13  = ["ohos-web-sys/api-13"]
api-14  = ["api-13", "ohos-web-sys/api-14"]
api-15  = ["api-14", "ohos-web-sys/api-15"]
api-16  = ["api-15", "ohos-web-sys/api-16"]
api-17  = ["api-16", "ohos-web-sys/api-17"]
api-18  = ["api-17", "ohos-web-sys/api-18"]
api-19  = ["api-18", "ohos-web-sys/api-19"]
api-20  = ["api-19", "ohos-web-sys/api-20"]
