[package]
name        = "ohos-web-binding"
version     = "0.1.0"
edition     = "2021"
license     = "MIT OR Apache-2.0"
description = "OpenHarmony's web binding for rust"

[dependencies]
ohos-web-sys    = { workspace = true }
bitflags        = { workspace = true }
ohos_enum_macro = { workspace = true }
