[package]
name        = "ohos-input-method-sys"
version     = "0.1.0"
edition     = "2021"
license     = "MIT OR Apache-2.0"
description = "OpenHarmony's input method binding for rust"

[dependencies]

[features]
default = []
api-15  = []
api-20  = ["api-15"]
