[package]
name        = "ohos-input-sys"
version     = "0.0.1"
edition     = "2021"
license     = "MIT OR Apache-2.0"
description = "OpenHarmony's multi modal input binding for rust"

[dependencies]

[features]
default = []
api-13  = []
api-14  = ["api-13"]
api-15  = ["api-14"]
api-20  = ["api-15"]
