[package]
name        = "ohos-bundle-sys"
version     = "0.0.2"
edition     = "2021"
license     = "MIT OR Apache-2.0"
description = "OpenHarmony's bundle binding for rust"

[dependencies]

[features]
default = []
api-13  = []
api-14  = ["api-13"]
api-20  = ["api-14"]
