[package]
name        = "ohos-xcomponent-sys"
version     = "0.0.2"
edition     = "2021"
license     = "MIT OR Apache-2.0"
description = "OpenHarmony's xcomponent binding for rust"

[dependencies]
ohos-arkui-sys         = { workspace = true }
ohos-accessibility-sys = { workspace = true }

[features]
default = []
api-13  = []
api-14  = ["api-13"]
api-15  = ["api-14"]
api-17  = ["api-15"]
api-18  = ["api-17"]
api-19  = ["api-18"]
api-20  = ["api-19"]
