[package]
name        = "ohos-web-sys"
version     = "0.0.1"
edition     = "2021"
license     = "MIT OR Apache-2.0"
description = "OpenHarmony's web binding for rust"

[dependencies]

[features]
default = []
api-14  = []
api-15  = ["api-14"]
api-18  = ["api-15"]
api-20  = ["api-18"]
